---
heat_template_version: newton

description: >
  Heat stack containing a group of groups of Nova instances.
  This is the top-level resource of a Cluster-as-a-Service deployment.

parameters:
  cluster_prefix:
    type: string
    label: Instance name prefix
    default: "cluster"
  cluster_groups:
    type: json
    label: List of dicts defining each group of nodes within the cluster
  cluster_keypair:
    type: string
    label: SSH key pair name for admin access to the cluster nodes
  cluster_az:
    type: string
    label: Availability zone
    default: nova
  cluster_net:
    type: json
    label: Network names and subnets to which the nodes should be attached
  volume_size_set_flag:
    type: boolean
    label: The volume size has been defined, for nodes that are booting from a volume.
    default: False
  volume_type_set_flag:
    type: boolean
    label: The volume type has been defined, for nodes that are booting from a volume.
    default: False
  security_groups_set_flag:
    type: boolean
    default: False

resources:
  cluster_group:
    type: OS::Heat::ResourceGroup
    properties:
      count:
        yaql:
          data: 
            cluster_groups: { get_param: cluster_groups }
          expression: $.data.cluster_groups.len()
      resource_def:
        type: cluster-group.yaml
        properties:
          cluster_prefix: { get_param: cluster_prefix }
          cluster_keypair: { get_param: cluster_keypair }
          cluster_az: { get_param: cluster_az }
          cluster_groups: { get_param: cluster_groups }
          cluster_net: { get_param: cluster_net }
          group_idx: "%index%"
          volume_size_set_flag: { get_param: volume_size_set_flag }
          volume_type_set_flag: { get_param: volume_type_set_flag }
          security_groups_set_flag: {  get_param: security_groups_set_flag }

outputs:
  cluster_group:
    description: Instance data for cluster node groups
    value: { get_attr: [cluster_group, group_data] }
